### ISSUE TITLE
Sugestão: ativar o github pages

### ISSUE THREAD

**Issue by nathabonfim59** [gabtapia/Data-e-Hora#1]
Hey! 

Excelente projeto, @gabtapia! 
Seria interessante se você ativasse o Github pages também. Assim poderemos ver os códigos rodando diretamente no navegador.

Segue o link da documentação de como fazer isso:
https://docs.github.com/pt/pages/getting-started-with-github-pages/creating-a-github-pages-site

**Comment by gabtapia** [comment]
Obrigado pela dica @nathabonfim59, Github pages ativado!
